[package]
name = "control"
version = "0.1.0"
edition = "2021"

[dependencies]
#nova-software-common = { git = "https://github.com/ERFSEDS/nova-software-common" }
nova-software-common = { path = "../../../nova-software-common" }

[features]
std = []
default = ["std"]
