[package]
name = "data-acquisition"
version = "0.1.0"
edition = "2018"

[dependencies]
cortex-m = "0.7"
embedded-hal = "0.2.6"
stm32f4xx-hal = { version = "0.10.0", features = ["stm32f412"] }
# state-machine = { path = "../state-machine" }
