
name: CI
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Rust Build
      run: |
        git clone https://github.com/ERFSEDS/nova-software-common ../nova-software-common
        rustup update stable && rustup default stable
        cargo build

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Rustfmt Check
      run: |
        git clone https://github.com/ERFSEDS/nova-software-common ../nova-software-common
        rustup update stable && rustup default stable && rustup component add rustfmt
        cargo fmt --all --manifest-path "Software/Cargo.toml" -- --check

  clippy_check:
    name: Clippy Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - id: component
        uses: actions-rs/components-nightly@v1
        with:
          component: clippy
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ steps.component.outputs.toolchain }}
            override: true
      - run: |
          git clone https://github.com/ERFSEDS/nova-software-common ../nova-software-common
          rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: "--manifest-path Software/Cargo.toml --all-features"

